# Generated by Django 4.2.1 on 2023-05-31 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureText',
            fields=[
                ('id_feature', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TextClass',
            fields=[
                ('id_text', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('id_feature', models.ManyToManyField(to='web.featuretext')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id_actions', models.AutoField(primary_key=True, serialize=False)),
                ('time_session', models.TimeField(auto_now=True)),
                ('id_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.textclass')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
        ),
    ]
