# Generated by Django 4.2.1 on 2023-06-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureText',
            fields=[
                ('id_feature', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TextClass',
            fields=[
                ('id_text', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('line_text', models.CharField(max_length=256)),
                ('language_text', models.CharField(max_length=256)),
                ('style_text', models.CharField(max_length=256)),
                ('tone_text', models.CharField(max_length=256)),
                ('informative_value', models.CharField(max_length=256)),
                ('emotional_coloring', models.CharField(max_length=256)),
                ('readability_text', models.CharField(max_length=256)),
                ('grammar_text', models.CharField(max_length=256)),
                ('syntax_text', models.CharField(max_length=256)),
                ('relevance', models.CharField(max_length=256)),
                ('vocabulary_text', models.CharField(max_length=256)),
                ('stylistics_text', models.CharField(max_length=256)),
                ('authorship_text', models.CharField(max_length=256)),
                ('lecture_hall', models.CharField(max_length=256)),
                ('intended_purpose', models.CharField(max_length=256)),
                ('context_text', models.CharField(max_length=256)),
                ('rhythm_text', models.CharField(max_length=256)),
                ('source_text', models.CharField(max_length=256)),
                ('impact_text', models.CharField(max_length=256)),
                ('shade_text', models.CharField(max_length=256)),
                ('depth_analysis', models.CharField(max_length=256)),
                ('writing_style', models.CharField(max_length=256)),
                ('main_idea', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserWeb',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id_actions', models.AutoField(primary_key=True, serialize=False)),
                ('time_session', models.TimeField(auto_now=True)),
                ('id_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.textclass')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userweb')),
            ],
        ),
    ]
